version: "3.8"

services:
  db:
    image: postgres:15
    container_name: zipup_postgres
    restart: always
    environment:
      POSTGRES_USER: teammate
      POSTGRES_PASSWORD: teampass123
      POSTGRES_DB: zipup_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: zipup_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin1234
    ports:
      - "8080:80"
    depends_on:
      - db

  app:
    build:
      context: ./postgres
    container_name: zipup_app
    depends_on:
      - db
    environment:
      - POSTGRES_USER=teammate
      - POSTGRES_PASSWORD=teampass123
      - POSTGRES_HOST=172.16.220.246
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
    volumes:
      - ./postgres:/app
    command: ["python", "database.py"]

volumes:
  pgdata:
